### PR TITLE
Allow double click to do nothing

### PR DESCRIPTION
**Pull request by matty-r**
As per: disable double click #116 . This also sets it up to allow other double click options - I will also pursuit allowing double click to launch korganizer.

### CODE REVIEW

**Comment by matty-r** [comment]
Also related: Disable Google Calendar / Double click to open browser #30

**Comment by Zren** [comment]
* You used Spaces instead of Tabs
* Config key needs to be `monthDayDoubleClick` (I'm moving away from snake case to camelcase).
* `"Double-click on Date"` is better than what I had, good idea. I'll need to manually fix all the .po files though (the translations should be good enough).
* We don't need camelcase for the enum values (`doNothing`). Might as well use Capitalized (`DoNothing`).
* `i18n("Open New Event In Browser")` does need to be more specific. Perhaps: `i18n("New Google Calendar Event (Web Browser)")`

**Comment by Zren** [comment]
I can fix everything up myself after merging though. If you haven't already updated it by tonight I'll do that.

**Comment by matty-r** [comment]
@Zren Thanks for the feedback, i'll take care of it. 
I'm also working on getting KOrganizer to launch, I've got it launching, and there is a '--view <url>' argument, but I can't find anywhere that stipulates what format that <url> should be. Can you point me in the right direction where I might find some detail about it?

**Comment by Zren** [comment]
Looks good.

**Comment by Zren** [comment]
Well need to create a bash/python script to launch `korganizer`, then run a dbus command after it opens. Here's my experiment with `kontact` (I forgot it's called korganizer). We'll need to rewrite for korganizer probably. Not sure if gdbus is always installed either, so probably needs to be a python dbus script. Though we could probably write a `dbus-send` command in bash.


```
kontact --module korganizer
gdbus call --session --dest=org.kde.kontact --object-path=/Calendar --method=org.kde.Korganizer.Calendar.showDate "(2020, 12, 31)"
```

As for what `korganizer --view=url` is:

* https://invent.kde.org/pim/korganizer/-/blob/master/src/koapp.cpp#L62

**Comment by Zren** [comment]
```bash
$ qdbus org.kde.kontact /Calendar
method void org.kde.Korganizer.Calendar.goDate(QString date)
method void org.kde.Korganizer.Calendar.goDate({D-Bus type "(iii)"} date)
method void org.kde.Korganizer.Calendar.openEventEditor(QString text)
method void org.kde.Korganizer.Calendar.openEventEditor(QString summary, QString description, QString uri, QString file, QStringList attendees, QString attachmentMimetype)
method void org.kde.Korganizer.Calendar.openEventEditor(QString summary, QString description, QStringList attachments)
method void org.kde.Korganizer.Calendar.openEventEditor(QString summary, QString description, QStringList attachments, QStringList attendees)
method void org.kde.Korganizer.Calendar.openEventEditor(QString summary, QString description, QStringList attachmentUris, QStringList attendees, QStringList attachmentMimetypes, bool attachmentIsInline)
method void org.kde.Korganizer.Calendar.openJournalEditor(QString text)
method void org.kde.Korganizer.Calendar.openJournalEditor(QString text, {D-Bus type "(iii)"} date)
method void org.kde.Korganizer.Calendar.openJournalEditor({D-Bus type "(iii)"} date)
method void org.kde.Korganizer.Calendar.openTodoEditor(QString text)
method void org.kde.Korganizer.Calendar.openTodoEditor(QString summary, QString description, QString uri, QString file, QStringList attendees, QString attachmentMimetype)
method void org.kde.Korganizer.Calendar.openTodoEditor(QString summary, QString description, QStringList attachments)
method void org.kde.Korganizer.Calendar.openTodoEditor(QString summary, QString description, QStringList attachments, QStringList attendees)
method void org.kde.Korganizer.Calendar.openTodoEditor(QString summary, QString description, QStringList attachmentUris, QStringList attendees, QStringList attachmentMimetypes, bool attachmentIsInline)
method void org.kde.Korganizer.Calendar.showDate({D-Bus type "(iii)"} date)
method void org.kde.Korganizer.Calendar.showEventView()
method void org.kde.Korganizer.Calendar.showJournalView()
method void org.kde.Korganizer.Calendar.showTodoView()
```

has `openEventEditor`, but I don't think it has a way to specify a date. It default to today's date.

**Comment by matty-r** [comment]
executable.exec(cmd) works to launch korganizer - can we just use that and pass the required args?

**Comment by Zren** [comment]
* Korganizer could already be running. We should support such a usecase.
* `korganizer` doesn't appear to support this feature when initializing anyways.
* `konsolekalendar` has an `--allow-gui` argument which I remember, we should check if it works. Look at my python script that wraps it for info.

**Comment by Zren** [comment]
* https://github.com/KDE/akonadi-calendar-tools/tree/master/konsolekalendar
* https://docs.kde.org/trunk5/en/pim/konsolekalendar/inserting.html

For some reason, `--allow-gui` does nothing but "insert"

**Comment by matty-r** [comment]
I'll get back into it later this afternoon and try to get this done. Thanks for the info mate, i'm sure i'll get to the bottom of it :)

**Comment by matty-r** [comment]
I've played around a bit and so far i've just been able to show korganizer, and go to the date:

```
gdbus call --session --dest=org.kde.korganizer --object-path=/korganizer/MainWindow_1 --method=org.qtproject.Qt.QWidget.raise
gdbus call --session --dest=org.kde.korganizer --object-path=/Calendar --method=org.kde.Korganizer.Calendar.goDate "(2020,12,31)"
```

There are a few problems, it doesn't actually update the UI of korganizer to reflect that the date has been selected. Also, trying to get it to create a new event doesn't start on the selected date, no matter the method chosen:

```
gdbus call --session --dest=org.kde.korganizer --object-path=/korganizer/MainWindow_1 --method=org.kde.KMainWindow.activateAction 'new_event'
```
or
```
gdbus call --session --dest=org.kde.korganizer --object-path=/Calendar --method=org.kde.Korganizer.Calendar.openEventEditor "(2020,12,31)"
```

At this point it seems to be more a problem with korganizer than the gdbus calls used.

**Comment by Zren** [comment]
* https://github.com/KDE/korganizer/blob/d12e378779f1bd92a84beaf7dc5583ad9f3e85dc/src/data/org.kde.Korganizer.Calendar.xml#L18
* https://github.com/KDE/korganizer/blob/d12e378779f1bd92a84beaf7dc5583ad9f3e85dc/src/calendarview.cpp#L987
* https://github.com/KDE/korganizer/blob/d12e378779f1bd92a84beaf7dc5583ad9f3e85dc/src/actionmanager.cpp#L1494

**Comment by matty-r** [comment]
I ended up raising it as a bug - it should be creating a new event based on the date selected:

- https://bugs.kde.org/show_bug.cgi?id=428818

**Pull request merged**
