### PR TITLE
Added Reminder Before Event Functionality

### PR DESCRIPTION
**Pull request by Zakgeki**
I added functionality that lets you get a reminder before a certain amount of time before an event. By default this option is off. I couldn't figure out why it wouldn't autopopulate the path for the reminder notification sound.

### CODE REVIEW

**Comment by Zren** [comment]
* `ConfigReminderSound.qml` is unnecessary. The config options are not in `main.xml`.
* `isRemindEvent()` uses the hardcoded `timeModel.currentTime` instead of reusing the `isSameMinute` function.

**Comment by Zakgeki** [comment]
>     * `ConfigReminderSound.qml` is unnecessary and not used.
> 
>     * The config options are not in `config/main.xml`.
> 
>     * `isRemindEvent()` uses the hardcoded `timeModel.currentTime` instead of reusing the `isSameMinute` function.
> 
>     * `lib/ConfigReminder.qml` isn't necesary, nor is it reusuable. Just create a `RowLayout {}` below a `ConfigNotification {}` with an indent.

Sorry, I've been busy. I'll implement those fixes soon.

**Comment by Zren** [comment]
Another bug I noticed was when:

```js
minutesBefore = 15
currentTime = "14:55" // Pseudo-code
startingTime = "15:10" // Pseudo-code
if (currentTime.getHours() == startingTime.getHours()
    && currentTime.getMinutes() == startingTime.getMinutes() - minutesBefore
) {
    // Won't work since we're comparing `14 == 15` and `55 == -5`
}
```

We need to do the following so that the `Date` object will roll over to `hours=14`.

```js
var reminderTime = new Date(startingTime)
reminderTime.setMinutes(reminderTime.getMinutes() - 15)
```

-----

Since I know what needs to be done, and I'm prepping for a release, I've cleaned it up for you.

We still need to parse reminders from google calendars and google events, but that'll be for another day. A global notification for all events should be fine for now.

I've defaulted it to not use a sfx, but I might reverse that later. The default value is `15mins`.

**Comment by Zakgeki** [comment]
Thanks for finishing this up, I've been really bogged down with school work and I'm not terribly familiar with JS or QML. Just enough to be dangerous, as it were ;).

**Pull request closed without merging**
