### PR TITLE
Update ru.po

### PR DESCRIPTION
**Pull request by aliger14**

### CODE REVIEW

**Comment by aliger14** [comment]
Я совсем не знаю английский язык, перевожу гуглом, не знаю структуру работы с github, поэтому сделайте как считаете нужным
I don't know English at all, I translate with Google, I don 't know the structure of working with github, so do as you see fit

**Comment by aliger14** [comment]
Спасибо.
Thanks. 
>Вторник, 3 марта 2020, 1:52 +03:00 от Chris Holland <notifications@github.com>:
> 
>Merged  #124 into master.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
-- <br/>aliger aliger

**Comment by aliger14** [comment]
Astronomical Events
Ошибка перевода:
Translation error:
Показывать автономические времена года (солнцестояния и равноденствия) — ошибка
Правильно вот так:
That's right like this:
Показывать а**стр**ономические времена года (солнцестояния и равноденствия)

**Comment by Zren** [comment]
Astronomical Events is not part of this repository, it's part of `kdeplasma-addons` which is a KDE project.

https://github.com/KDE/kdeplasma-addons/tree/master/plasmacalendarplugins/astronomical

To translate that project, look for `plasma_calendar_astronomicalevents` in the KDE translations SVN. Probably under the `kde-workspace` folder.

* https://l10n.kde.org/stats/gui/trunk-kf5/team/ru/
* https://l10n.kde.org/stats/gui/trunk-kf5/team/ru/kde-workspace/
* https://websvn.kde.org/*checkout*/trunk/l10n-kf5/ru/messages/kde-workspace/plasma_calendar_astronomicalevents.po

As for how to contribute your changes, please contact the KDE translation team.

* https://community.kde.org/Get_Involved/translation
* https://rabbitictranslator.com/wordpress/index.php/2020/01/19/contributing-to-kde-localization/

Now that I check `plasma_calendar_astronomicalevents.po`, it appears `автономические` => `астрономические` has already been fixed.

**Comment by aliger14** [comment]
Спасибо. Thanks.
  
>Четверг, 5 марта 2020, 19:37 +03:00 от Chris Holland <notifications@github.com>:
> 
>To translate that project, look for plasma_calendar_astronomicalevents in the KDE translations SVN. Probably under the kde-workspace folder.
>*  https://l10n.kde.org/stats/gui/trunk-kf5/team/ru/
>*  https://l10n.kde.org/stats/gui/trunk-kf5/team/ru/kde-workspace/
>*  https://websvn.kde.org/*checkout*/trunk/l10n-kf5/ru/messages/kde-workspace/plasma_calendar_astronomicalevents.po
 
>*  
>Now that I check plasma_calendar_astronomicalevents.po, it appears автономические => астрономические has already been fixed.  
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
-- <br/>aliger aliger

**Pull request merged**
