### PR TITLE
Custom calendar title

### PR DESCRIPTION
**Pull request by matty-r**
Changes made as per your review. 

Hopefully this is what you meant by creating a branch :)

### CODE REVIEW

**Comment by Zren** [comment]
To be honest, we don't need `monthOtherCustomTitleFormat`. The user is rarely viewing "November, 2021". The main issue is the date format for the current month as US and EU have different order.

**Comment by Zren** [comment]
Also, whenever you have a:

```
if (!isTrue) {
  falseCode()
} else {
  trueCode()
}
```

It's better to do `if (isTrue) { trueCode() } else { falseCode() }` as it's easier to read.

**Comment by matty-r** [comment]
> Also, whenever you have a:
> 
> ```
> if (!isTrue) {
>   falseCode()
> } else {
>   trueCode()
> }
> ```
> 
> It's better to do `if (isTrue) { trueCode() } else { falseCode() }` as it's easier to read.

That's fair. Not sure why I did it that way.

As for the Other month, maybe I could just parse out the 'dd' from the Current month and use that instead of having a seperate value.

**Comment by Zren** [comment]
I've realized I can use font colors here too:



* `'<font color="#3daee9">'yyyy'</font>' MMMM d`

It makes it look a bit like the Gnome Calendar mockup from a while back.

https://zren.github.io/2019/04/06/side-calendar-work-in-progress

To bold the month use `<b>`.

Eg: `'<b>'MMMM'</b>' '<font color="#3daee9">'yyyy'</font>'`

**Pull request merged**
