### PR TITLE
Some cleaning up

### PR DESCRIPTION
**Pull request by matty-r**
- Adjusted a majority of snake_case to camelCase.
- Changed the Timer ConfigCheckBox + RowLayout to ConfigNotification - this disables the sfx option correctly when timer is disabled.

### CODE REVIEW

**Comment by Zren** [comment]
The reason I have not refactored the config keys is because that would reset the settings for users on upgrade. You would need to keep the existing config keys for ___ versions and migrate them to the new config keys to do this properly. I'm not gonna do that.

> Changed the Timer ConfigCheckBox + RowLayout to ConfigNotification - this disables the sfx option correctly when timer is disabled.

No.

**Comment by Zren** [comment]
Sorry I worded it like I was in the middle of a migration. What I meant was that all new config keys should be camelcase. I can't actually migrate the old snakecase config keys without a bunch of work.

**Comment by matty-r** [comment]
Ok, that's fair. Probably shouldn't have just ran with it. Ha ha.

Can I ask why we can't change the timer option?

**Comment by Zren** [comment]
Because it's not a toggle for the Timer notification but the widget itself. The timer could get another row of options too (preset timers).

**Comment by matty-r** [comment]
Not sure I follow. If the widget is disabled then you wouldn't need to set a sound for it.

**Comment by Zren** [comment]
The current layout may be identical to ConfigNotification, but it is not guaranteed that the `[x] NotificationLabel:` layout won't change.

I guess we could add `enabled: show_timer` to the `ConfigSound` to display the SFX as disabled.

**Pull request closed without merging**
